version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: plataforma_n8n
    restart: always
    ports:
      - "5490:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: plataforma_n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
